### ISSUE TITLE
Roadmap & Top open questions about the future of PrototypeML 

### ISSUE THREAD

**Issue by DanielRHarris** [PrototypeML/PrototypeML#1]
Hey Everyone,

Here's a little update on where we're heading and the top questions we have for you about the future of the PrototypeML project. We'd also love to hear your thoughts and suggestions on the project and what direction you'd like to see it move! Join our community Discord to discuss: https://discord.gg/zq8uqSf

**Top Open Questions:**

**1. How should we handle If/Else blocks, Loops & other indented code blocks?**
Several options were raised (combo block/mutator, special if & end-if components), but we're not yet particularly happy with any of them.
**2. How should we handle duplication of code when multiple mutators are utilized in a single block?**
Do you want to be able to enclose code in init() and forward() sections in ${noDup} & ${/noDup} to prevent duplication?
**3. What other shortcuts/tweaks/features do you use frequently that could be sped up using the tool?** 
**4. What feature do you most find helpful? What feature do you find least helpful/harmful?**

**Roadmap:**
- Upcoming:
  - Project stability fixes toward beta release (million little bugs to solve, mostly visual, some technical)
  - Creation of mutators for all major libraries
  - Packages update (change versions, apply semantic versioning restraints on versions, visual tweaks, etc)
- Future Features:
  - Undo/redo
  - Cut/copy/paste/select multiple
  - Parameter validation (data type, shape, etc)
  - Automatic PyTorch model layer shape validation (think AutoGrad but for input/output shape validation)
  - Model weight saving for component weight zoo
  - ONNX import/export
  - Code Importing (import an existing codebase and automatically divide into blocks/mutators)
  - API (project creation API for automatic creation/maintenance of mutators for external codebases)
  - Upload project code to Github
  - Live collaborative editing

**Comment by michaelklachko** [comment]
Is this project still alive?

**Comment by DanielRHarris** [comment]
> Is this project still alive?

Definitely still alive and under heavy development — check out our NeurIPS demonstration: https://prototypeml.com/neurips2020

**Comment by michaelklachko** [comment]
I see the last commit was 5 months ago. Is it no longer open source?

**Comment by DanielRHarris** [comment]
Haven’t had the bandwidth to update the documentation (that’s all that is stored here) — the tool itself has been improved significantly in the last six months. We haven’t released the code yet, how best to do that is still to be decided. I don’t read this often, so if you have any further questions, please email questions@prototypeml.com, thanks for your interest!
